name: Auto Label and Comment on New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  auto-label-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add enhancement label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['enhancement']
            });

      - name: Add review comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '@Saumy1905 will review this issue'
            });
